import { DatePipe, NgClass } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { CompassRepository, RadarRow, Signal, World } from '../../core/compass/compass.repository';
import { RoleService } from '../../core/compass/role.service';

@Component({
	imports: [DatePipe, FormsModule, NgClass, RouterLink],
	template: `<section class="page radar-page">
		<header class="page-header"><div><p class="eyebrow">COMPASS / INTELLIGENCE</p><h1>PROPERTY RADAR</h1><p>Live OUTLAND property intelligence</p></div><button class="primary" (click)="showSignal.set(true)" [disabled]="!roles.canAnalyze">+ ADD SIGNAL</button></header>
		<div class="kpis"><article><span>ACTIVE</span><strong>{{ activeCount() }}</strong></article><article><span>HOT</span><strong>{{ countRecommendation('HOT') }}</strong></article><article><span>SHORTLIST</span><strong>{{ countStatus('SHORTLIST') }}</strong></article><article><span>DD</span><strong>{{ countStatus('DD') }}</strong></article><article><span>BLOCKED</span><strong>{{ countRecommendation('BLOCKED') }}</strong></article></div>
		<div class="toolbar"><input [(ngModel)]="search" placeholder="Search title, place, region"><select [(ngModel)]="world"><option value="">ALL WORLDS</option>@for (item of radarWorlds(); track item.id) {<option [value]="item.code">{{ item.name }}</option>}</select><select [(ngModel)]="recommendation"><option value="">ALL RECOMMENDATIONS</option>@for (item of recommendations; track item) {<option [value]="item">{{ item }}</option>}</select><select [(ngModel)]="status"><option value="">ALL STATUSES</option>@for (item of statuses; track item) {<option [value]="item">{{ item }}</option>}</select><label>Min score <input type="number" [(ngModel)]="minScore"></label><label>Min confidence <input type="number" [(ngModel)]="minConfidence"></label><button class="quiet" (click)="reset()">Reset filters</button></div>
		<div class="subnav"><button [class.active]="panel() === 'radar'" (click)="panel.set('radar')">RADAR <b>{{ filtered().length }}</b></button><button [class.active]="panel() === 'signals'" (click)="panel.set('signals')">SIGNAL INBOX <b>{{ signals().length }}</b></button></div>
		@if (loading()) { <div class="state">Loading live Radar...</div> } @else if (error()) { <div class="state error">{{ error() }}</div> } @else if (panel() === 'radar') {
			@if (filtered().length) { <div class="candidate-list">@for (row of filtered(); track row.id) {<a class="candidate-row" [routerLink]="['/candidates', row.id]"><div><span class="world">{{ row.world_code }}</span><h2>{{ row.title }}</h2><p>{{ row.settlement || row.municipality || row.region || 'Location unknown' }}</p></div><div><span class="label">ASKING</span><strong>{{ money(row.asking_price, row.currency) }}</strong><small>{{ area(row.area_m2) }} · {{ money(row.price_per_m2, row.currency) }}/m²</small></div><div class="metric"><span>COMPASS</span><strong>{{ number(row.compass_score) }}</strong></div><div class="metric"><span>CONFIDENCE</span><strong>{{ percent(row.confidence_percent) }}</strong></div><div><span class="badge" [ngClass]="badge(row.recommendation)">{{ row.recommendation }}</span><small>{{ row.critical_failed_count || 0 }} critical fails · {{ row.critical_unknown_count || 0 }} critical unknowns</small></div><div><span class="label">LAST SEEN</span><small>{{ row.last_seen_at ? (row.last_seen_at | date:'dd MMM') : '—' }}</small></div>@if(row.id && sourceUrls()[row.id]){<button type="button" class="quiet" (click)="openListing($event, sourceUrls()[row.id!])">LISTING ↗</button>}</a>}</div> } @else { <div class="state">No candidates match these filters.</div> }
		} @else { <div class="signal-list">@for (signal of signals(); track signal.id) {<article><div><span class="world">{{ signal.status }}</span><h2>{{ signal.raw_title || 'Untitled signal' }}</h2><p>{{ signal.source_name || 'Unknown source' }} · {{ signal.discovered_at | date:'dd MMM yyyy' }}</p></div><div>{{ money(signal.raw_price, signal.raw_currency) }} · <small>{{ area(signal.raw_area_m2) }}</small></div><div><select [(ngModel)]="promotionWorld[signal.id]" [disabled]="!roles.canAnalyze"><option value="">Select World</option>@for (item of radarWorlds(); track item.id) {<option [value]="item.id">{{ item.name }}</option>}</select><button class="quiet" (click)="promote(signal)" [disabled]="!promotionWorld[signal.id] || !roles.canAnalyze">PROMOTE</button></div></article>} @empty {<div class="state">No captured signals yet.</div>}</div> }
		@if (showSignal()) {<div class="modal-backdrop"><form class="modal" (ngSubmit)="saveSignal()"><button type="button" class="close" (click)="showSignal.set(false)">×</button><p class="eyebrow">CAPTURE OPPORTUNITY</p><h2>ADD SIGNAL</h2><label>Source URL<input name="url" [(ngModel)]="draft.source_url" type="url"></label><label>Source name<input name="source" [(ngModel)]="draft.source_name"></label><label>World<select name="draftWorld" [(ngModel)]="draft.world_id"><option [ngValue]="null">Unassigned</option>@for (item of radarWorlds(); track item.id) {<option [value]="item.id">{{ item.name }}</option>}</select></label><label>Listing title<input name="title" [(ngModel)]="draft.raw_title"></label><label>Location<input name="location" [(ngModel)]="draft.raw_location"></label><label>Price (whole EUR)<input name="price" [(ngModel)]="draft.raw_price" type="number" min="0" step="1" placeholder="29900"></label><label>Area m² (whole number)<input name="area" [(ngModel)]="draft.raw_area_m2" type="number" min="0" step="1" placeholder="1800"></label><label>Notes<textarea name="description" [(ngModel)]="draft.raw_description"></textarea></label><p class="form-error">{{ formError() }}</p><button class="primary" type="submit">SAVE SIGNAL</button></form></div>}
	</section>`,
	styleUrl: './radar.page.scss'
})
export default class RadarPage {
	readonly repo = inject(CompassRepository); readonly roles = inject(RoleService); readonly rows = signal<RadarRow[]>([]); readonly worlds = signal<World[]>([]); readonly signals = signal<Signal[]>([]); readonly sourceUrls = signal<Record<string, string>>({}); readonly loading = signal(true); readonly error = signal(''); readonly panel = signal<'radar' | 'signals'>('radar'); readonly showSignal = signal(false); readonly formError = signal('');
	search = ''; world = ''; recommendation = ''; status = ''; minScore?: number; minConfidence?: number; promotionWorld: Record<string, string> = {}; readonly recommendations = ['HOT', 'STRONG', 'WATCH', 'LOW', 'BLOCKED', 'UNSCORED']; readonly statuses = ['NEW', 'REVIEWED', 'SHORTLIST', 'DD', 'NEGOTIATION', 'ACQUIRED']; draft: { source_url?: string; source_name?: string; world_id?: string | null; raw_title?: string; raw_location?: string; raw_price?: number; raw_area_m2?: number; raw_description?: string } = {};
	readonly radarWorlds = computed(() => this.worlds().filter((world) => world.radar_enabled)); readonly filtered = computed(() => this.rows().filter((row) => { const text = [row.title, row.settlement, row.municipality, row.region].join(' ').toLowerCase(); return (!this.search || text.includes(this.search.toLowerCase())) && (!this.world || row.world_code === this.world) && (!this.recommendation || row.recommendation === this.recommendation) && (!this.status || row.status === this.status) && (!this.minScore || (row.compass_score ?? -1) >= this.minScore) && (!this.minConfidence || (row.confidence_percent ?? -1) >= this.minConfidence); }).sort((a, b) => this.rank(b) - this.rank(a)));
	constructor() { void this.refresh(); void this.roles.load(); } async refresh() { try { this.loading.set(true); const [rows, worlds, signals] = await Promise.all([this.repo.radar(), this.repo.worlds(), this.repo.signals()]); this.rows.set(rows); this.worlds.set(worlds); this.signals.set(signals); const candidateIds = rows.map((row) => row.id).filter((id): id is string => !!id); const sources = await this.repo.sourceUrls(candidateIds); const urls: Record<string, string> = {}; for (const source of sources) { if (source.source_url && !urls[source.candidate_id]) { urls[source.candidate_id] = source.source_url; } } this.sourceUrls.set(urls); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Unable to load Property Radar.'); } finally { this.loading.set(false); } }
	countRecommendation(value: string) { return this.rows().filter((row) => row.recommendation === value).length; } countStatus(value: string) { return this.rows().filter((row) => row.status === value).length; } activeCount() { return this.rows().filter((row) => !['ACQUIRED', 'REJECTED', 'ARCHIVED', 'SOLD'].includes(row.status ?? '')).length; } reset() { this.search = this.world = this.recommendation = this.status = ''; this.minScore = this.minConfidence = undefined; } rank(row: RadarRow) { return row.recommendation === 'BLOCKED' ? -1 : ({ HOT: 600, STRONG: 500, WATCH: 400, LOW: 300, UNSCORED: 100 }[row.recommendation ?? ''] ?? 0) + (row.compass_score ?? 0); }
	async saveSignal() { if (!this.draft.source_url && !this.draft.raw_title) { this.formError.set('Add a source URL or a meaningful listing title.'); return; } try { await this.repo.createSignal({ ...this.draft, raw_currency: 'EUR' }); this.showSignal.set(false); this.draft = {}; await this.refresh(); } catch (error) { this.formError.set(error instanceof Error ? error.message : 'Signal could not be saved.'); } } async promote(signal: Signal) { try { const id = await this.repo.promoteSignal(signal.id, this.promotionWorld[signal.id], signal.raw_title ?? undefined); location.assign(`/candidates/${id}`); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Signal could not be promoted.'); } }
	openListing(event: Event, url: string) { event.preventDefault(); event.stopPropagation(); window.open(url, '_blank', 'noopener,noreferrer'); }
	money(value: number | null, currency: string | null = 'EUR') { return value == null ? '—' : new Intl.NumberFormat('en-IE', { style: 'currency', currency: currency ?? 'EUR' }).format(value); } area(value: number | null) { return value == null ? '—' : `${new Intl.NumberFormat('en-IE').format(value)} m²`; } number(value: number | null) { return value == null ? '—' : Math.round(value).toString(); } percent(value: number | null) { return value == null ? '—' : `${Math.round(value)}%`; } badge(value: string | null) { return `badge-${(value ?? 'UNSCORED').toLowerCase()}`; }
}
